/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9b580503-ee81-40d3-ba0f-b62fd5eacbe5",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tutzX9Ekf",
    "aws_user_pools_web_client_id": "178cp5shill95s3h753snrqotd",
    "oauth": {}
};


export default awsmobile;
